import type { Metadata } from "next";
import '../globals.css';

export const metadata: Metadata = {
    title: "Morgan Clarke Portfolio",
    description: "Generated by Next JS + Sanity IO",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
            <body>{children}
            </body>
        </html>
    );
}
